### ISSUE TITLE
Need --feda option.

### ISSUE THREAD

**Issue by kozdincer** [kozdincer/binali#25]
When --feda options used, script's outpute should be this[0] quote.
[0] https://github.com/kozdincer/binali/commit/51ae3b8f3b85b831a05c0c29f50e52e8891494a9

**Comment by ulgens** [comment]
I will be working on this today, if you didn't start yet.

**Comment by kozdincer** [comment]
https://github.com/kozdincer/binali/pull/26 Fix that.
Thanks for interest.
