### ISSUE TITLE
PyPI Support

### ISSUE THREAD

**Issue by beucismis** [kozdincer/binali#29]
Projeyi PyPI'ye yükledim. Bunun için önceden izin almam gerekiyor muydu bilmiyorum? İnanın şuan yazarken aklıma geldi... İyi eğlenceler :)

PyPI: https://pypi.org/project/binali
Fork: https://github.com/beucismis-archive/binali

```
$ pip3 install --user binali
```

**Comment by serdardalgic** [comment]
Hayat sizi acaba nasil bir noktaya sürükledi ki projeyi PyPI'ya yükleme ihtiyaci duydunuz, bilemiyorum 😅
Cevaben Binali Bey'in su videosunu yüklemek istiyorum: 

https://user-images.githubusercontent.com/121254/113782108-f1bfc280-9731-11eb-849d-d09ed8ba9fa3.mp4

**Comment by serdardalgic** [comment]
Ha, gereken cevabi zaten bu millet 15 Temmuzda verdi, di mi @kozdincer hocam? Sadece soruyorum.

**Comment by kozdincer** [comment]
Kesinlikle. @serdardalgic

**Comment by kozdincer** [comment]
@beucismis bizim depoyada bit PR atinda bizde alalim son eklemeleri.

**Comment by serdardalgic** [comment]
> Kesinlikle. @serdardalgic


https://user-images.githubusercontent.com/121254/113782856-23855900-9733-11eb-8d98-2f7191270173.mp4

**Comment by beucismis** [comment]
> Hayat sizi acaba nasil bir noktaya sürükledi ki projeyi PyPI'ya yükleme ihtiyaci duydunuz, bilemiyorum sweat_smile
> Cevaben Binali Bey'in su videosunu yüklemek istiyorum:
> binalicevapveremedim.mp4

Sorunun bir benzerini ben de size sormak isterim :)

**Comment by beucismis** [comment]
@kozdincer seve seve...

**Comment by beucismis** [comment]
#30
